[WIP] Prepare Asset Swapper for RFQM
0xProject/protocol pull request #175
Opened 2021-03-16 21:04 UTC by phil-ociraptor

## Description

A set of changes to prepare Asset Swapper for RFQM. Currently a draft

## Testing instructions

Test all RFQT flows for regression

## Types of changes

* New feature (non-breaking change which adds functionality)

## Checklist:

-   [x] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

2021-03-16 21:10 UTC, phil-ociraptor commented
> Could we just rename `RfqtMakerAssetOfferings` to `RfqMakerAssetOfferings`?

Absolutely. Also considering renaming `RfqtRequestOpts` to `RfqRequestOpts`

2021-03-18 23:15 UTC, PirosB3 requested changes

2021-03-24 17:08 UTC, phil-ociraptor commented on packages/asset-swapper/src/utils/quote_requestor.ts
> +        const standardUrls = Object.keys(assetOfferings).map(
So I believe in the line: 
```
const partialLogEntry = { url: typedMakerUrl.url, quoteType, requestParams, isBlacklisted }

```

The field `requestParams` already contains the `isLastLook` parameter, as the `requestParams` field is generated by the `makeQueryParameters` function.

Should this be sufficient for logging?

2021-03-31 20:31 UTC, closed without merging

2021-03-31 20:31 UTC, phil-ociraptor commented
This has been completed by #187