feat/optimism [TKR-280]
0xProject/protocol pull request #385
Opened 2021-12-23 05:14 UTC by shawnxin89

## Description

[TKR-280]

Optimism support:

Add uniswap V3 

## Testing instructions

## Types of changes

## Checklist:

-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

2021-12-23 10:39 UTC, kimpers requested changes

2021-12-23 10:39 UTC, kimpers commented on packages/contract-addresses/addresses.json
> +        "exchangeProxy": "0xdef1abe32c034e558cdd535791643c58a13acc10",
EP verification on Optimistic Etherscan looks a bit funky https://optimistic.etherscan.io/address/0xdef1abe32c034e558cdd535791643c58a13acc10#code. Can we still verify it properly?

2021-12-23 10:39 UTC, kimpers commented on packages/contract-addresses/addresses.json
> +        }
I could be wrong but I don't think we use checksummed addresses in this file

2021-12-24 07:35 UTC, dorothy-zbornak approved these changes
:+1: :eye: :lips: :eye: :+1:

2021-12-24 07:35 UTC, dorothy-zbornak commented on packages/contract-addresses/addresses.json
> +    "69": {
Do we really need the testnet as an entry? Can we remove this?

2021-12-24 09:39 UTC, kimpers approved these changes
Awesome work! 🙏

2021-12-24 16:28 UTC, merged