[TKR-275] Add Geist on Fantom
0xProject/protocol pull request #398
Opened 2022-01-18 00:14 UTC by cece-z

## Description

Add Geist on Fantom

## Testing instructions

## Types of changes

## Checklist:

-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

2022-02-09 13:30 UTC, kimpers requested changes
Awesome work on this! Just some minor comments and nits (feel free to ignore) 🙏

2022-02-09 13:30 UTC, kimpers commented on packages/asset-swapper/src/utils/market_operation_utils/geist_utils.ts
> +    ]);
SUPER NIT: If you move this outside the function it only gets initialized once, whereas now it's initialized on every call

2022-02-09 13:30 UTC, kimpers commented on packages/protocol-utils/src/transformer_utils.ts
> +    Geist,
This is a 1:1 Aave V2 fork right? Then you don't need to add anything here.

This list needs to match [BridgeProtocols.sol](https://github.com/0xProject/protocol/blob/development/contracts/zero-ex/contracts/src/transformers/bridges/BridgeProtocols.sol#L26-L55) so we only add unique integrations that require a deployment :)

2022-02-09 13:30 UTC, kimpers commented on packages/asset-swapper/src/utils/market_operation_utils/orders.ts
> +            return encodeBridgeSourceId(BridgeProtocol.Geist, 'Geist');
If this is a 1:1 fork you can use `BridgeProtocol.AaveV2` just like we have done with the gazillion Uniswap V2 forks above 😄 
```suggestion
            return encodeBridgeSourceId(BridgeProtocol.AaveV2, 'Geist');
```

2022-02-22 10:06 UTC, kimpers commented on packages/asset-swapper/src/utils/market_operation_utils/constants.ts
> +        [ChainId.Fantom]: '0xd8321AA83Fb0a4ECd6348D4577431310A6E0814d',
NIT: we try to lowercase addresses

2022-03-01 22:25 UTC, dekz approved these changes

2022-03-02 06:34 UTC, merged