chore: Bump asset swapper fast-abi dep
0xProject/protocol pull request #404
Opened 2022-01-24 23:03 UTC by rhinodavid

## Description

Bump `@0x/asset-swapper` from `0.0.2` to `0.0.3`.

## Testing instructions

## Types of changes

## Checklist:

-   [ ] Prefix PR title with `[WIP]` if necessary.
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation as needed.
-   [ ] Add new entries to the relevant CHANGELOG.jsons.

2022-01-26 12:41 UTC, kimpers requested changes

2022-01-26 12:41 UTC, kimpers commented on packages/asset-swapper/CHANGELOG.json
> +                "note": "Bump asset swapper fast-abi dependency version"
NIT:
```suggestion
                "note": "Bump asset swapper fast-abi dependency version",
                "pr": 404
```

2022-01-26 12:41 UTC, kimpers commented on packages/asset-swapper/package.json
> +        "fast-abi": "^0.0.3",
you need to do `yarn install` to update the `yarn.lock` file accordingly

2022-03-02 03:40 UTC, dekz commented
`development` has been updated to `0.0.4` and `node:16`

2022-03-02 03:40 UTC, closed without merging